Repository virtual-kubelet/systemk, pull requests merged in 2020-12, with the labels that each got.

#4 Introduce a no-op package manager
  pkg/packages/noop.go
  systemd/provider.go
Labels: enhancement

#8 node: fix known labels
  systemd/node.go
Labels: bug, enhancement

#12 system: fix OS image
  pkg/system/system.go
  pkg/system/system_test.go
  pkg/system/testdata/os-release-rhel77
  pkg/system/testdata/os-release-ubuntu2004
Labels: bug

#14 watch configmaps and secrets
  README.md
  go.mod
  go.sum
  k3s/uptimed.yaml
  main.go
  pkg/manager/manager.go
  systemd/pod.go
  systemd/provider.go
  systemd/provider_test.go
  systemd/testdata/provider/uptimed.units
  systemd/testdata/provider/uptimed.yaml
  systemd/testdata/uptimed-config.yaml
  systemd/volumes.go
  systemd/watch.go
  systemd/watch_test.go
Labels: enhancement

#34 provider: use informers to read/watch secrets and configmaps
  systemd/pod.go
  systemd/provider.go
  systemd/volumes.go
  systemd/watch.go
  systemd/watch_test.go
Labels: enhancement

#33 feature: clean-up volumes on Pod deletion
  main.go
  systemd/env.go
  systemd/node.go
  systemd/pod.go
  systemd/provider.go
  systemd/provider_test.go
  systemd/unit.go
  systemd/volumes.go
Labels: enhancement
