Repository virtual-kubelet/systemk, pull requests merged in 2021-01, with the labels that each got.

#52 abs path
  README.md
  k3s/uptimed.yaml
  pkg/packages/archlinux.go
  pkg/packages/debian.go
  pkg/packages/debian_test.go
  pkg/packages/noop.go
  pkg/packages/packages.go
  pkg/packages/remote.go
  pkg/packages/remote_test.go
  systemd/pod.go
Labels: enhancement

#32 pod: fix status update
  systemd/unit.go
Labels: bug, help wanted

#61 pod: fix unwatch
  systemd/provider.go
  systemd/testdata/provider/hello.units
  systemd/testdata/provider/hello.yaml
  systemd/watch.go
  systemd/watch_test.go
Labels: bug

#67 node: container runtime feeds from systemctl
  internal/system/system.go
Labels: bug

#69 node: retrieve logs from journal socket
  .github/workflows/go.yml
  cmd/http.go
  internal/provider/pod.go
  internal/testdata/provider/hello.units
  internal/testdata/provider/hello.yaml
Labels: enhancement

#70 node: support following logs
  cmd/http.go
  internal/provider/log.go
  internal/provider/pod.go
  internal/provider/provider.go
Labels: enhancement

#72 node: machine ID is set in Node info
  internal/provider/node.go
  internal/provider/provider.go
Labels: enhancement

#71 main: fail fast if systemd is not running
  main.go
Labels: bug
